In [4]:
import geopandas as gpd
import matplotlib.pyplot as plt

In [2]:
gdf_poblacion = gpd.read_file("datos/poblacion_distrito.geojson")

In [3]:
print("Shape:", gdf_poblacion.shape)

print("\nColumnas:")
print(gdf_poblacion.columns.tolist())

print("\nInfo:")
gdf_poblacion.info()

print("\nValores nulos:")
display(gdf_poblacion.isna().sum())

print("\nValores únicos:")
display(gdf_poblacion.nunique())

print("\nHead:")
display(gdf_poblacion.head())

Shape: (491, 9)

Columnas:
['codigo_pcd', 'id', 'nom_es', 'value', 'source', 'qualitative_value', 'notes', 'label_value', 'geometry']

Info:
<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 491 entries, 0 to 490
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   codigo_pcd         491 non-null    str
 1   id                 491 non-null    int32
 2   nom_es             491 non-null    str
 3   value              491 non-null    float64
 4   source             491 non-null    int32
 5   qualitative_value  0 non-null      object
 6   notes              491 non-null    str
 7   label_value        491 non-null    str
 8   geometry           491 non-null    geometry
dtypes: float64(1), geometry(1), int32(2), object(1), str(4)
memory usage: 41.2+ KB

Valores nulos:

codigo_pcd             0
id                     0
nom_es                 0
value                  0
source                 0
qualitative_value    491
notes                  0
label_value            0
geometry               0
dtype: int64

Valores únicos:

codigo_pcd           491
id                   491
nom_es               396
value                491
source                 1
qualitative_value      0
notes                  1
label_value          482
geometry             491
dtype: int64

Head:

,codigo_pcd,id,nom_es,value,source,qualitative_value,notes,label_value,geometry
0,10101,3293,Carmen,2728.507629,5,None,,2 729,"MULTIPOLYGON (((-84.06568 9.93964, -84.06558 9..."
1,10102,3292,Merced,15601.826028,5,None,,15 602,"MULTIPOLYGON (((-84.07845 9.94159, -84.07857 9..."
2,10111,3302,San Sebastián,42488.687801,5,None,,42 489,"MULTIPOLYGON (((-84.09622 9.90614, -84.09609 9..."
3,10201,3303,Escazú,13003.526323,5,None,,13 004,"MULTIPOLYGON (((-84.13556 9.92422, -84.1356 9...."
4,10202,3304,San Antonio,28717.190423,5,None,,28 717,"MULTIPOLYGON (((-84.11975 9.91097, -84.11892 9..."

In [6]:
gdf_poblacion = gdf_poblacion.drop(columns=[
    "id",
    "value",
    "source",
    "qualitative_value",
    "notes",
    "geometry"
])

In [10]:
print("codigo_pcd")
print("Mínimo:", gdf_poblacion["codigo_pcd"].min())
print("Máximo:", gdf_poblacion["codigo_pcd"].max())

print("\nnom_es")
print("Mínimo:", gdf_poblacion["nom_es"].min())
print("Máximo:", gdf_poblacion["nom_es"].max())

print("\nlabel_value")
print("Mínimo:", gdf_poblacion["label_value"].min())
print("Máximo:", gdf_poblacion["label_value"].max())

codigo_pcd
Mínimo: 10101
Máximo: 70605

nom_es
Mínimo: Acapulco
Máximo: Ángeles

label_value
Mínimo: 415
Máximo: 91596

In [11]:
print("\nHead:")
display(gdf_poblacion.head())

Head:

  codigo_pcd         nom_es  label_value
0      10101         Carmen         2729
1      10102         Merced        15602
2      10111  San Sebastián        42489
3      10201         Escazú        13004
4      10202    San Antonio        28717

In [12]:
gdf_poblacion.to_csv(
    "poblacion_distritos.csv",
    index=False,
    encoding="utf-8-sig"
)

In [13]:
gdf_densidad = gpd.read_file("datos/densidad_poblacion_distrito.geojson")

In [14]:
print("Shape:", gdf_densidad.shape)

print("\nColumnas:")
print(gdf_densidad.columns.tolist())

print("\nInfo:")
gdf_densidad.info()

print("\nValores nulos:")
display(gdf_densidad.isna().sum())

print("\nValores únicos:")
display(gdf_densidad.nunique())

print("\nHead:")
display(gdf_densidad.head())

Shape: (491, 9)

Columnas:
['codigo_pcd', 'id', 'nom_es', 'value', 'source', 'qualitative_value', 'notes', 'label_value', 'geometry']

Info:
<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 491 entries, 0 to 490
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   codigo_pcd         491 non-null    str
 1   id                 491 non-null    int32
 2   nom_es             491 non-null    str
 3   value              491 non-null    float64
 4   source             491 non-null    int32
 5   qualitative_value  0 non-null      object
 6   notes              491 non-null    str
 7   label_value        491 non-null    str
 8   geometry           491 non-null    geometry
dtypes: float64(1), geometry(1), int32(2), object(1), str(4)
memory usage: 41.4+ KB

Valores nulos:

codigo_pcd             0
id                     0
nom_es                 0
value                  0
source                 0
qualitative_value    491
notes                  0
label_value            0
geometry               0
dtype: int64

Valores únicos:

codigo_pcd           491
id                   491
nom_es               396
value                489
source                 1
qualitative_value      0
notes                  1
label_value          489
geometry             491
dtype: int64

Head:

,codigo_pcd,id,nom_es,value,source,qualitative_value,notes,label_value,geometry
0,10101,3293,Carmen,1831.21,5,None,1,"1 831,21","MULTIPOLYGON (((-84.06568 9.93964, -84.06558 9..."
1,10102,3292,Merced,7091.74,5,None,1,"7 091,74","MULTIPOLYGON (((-84.07845 9.94159, -84.07857 9..."
2,10111,3302,San Sebastián,10702.44,5,None,1,"10 702,44","MULTIPOLYGON (((-84.09622 9.90614, -84.09609 9..."
3,10201,3303,Escazú,2870.54,5,None,1,"2 870,54","MULTIPOLYGON (((-84.13556 9.92422, -84.1356 9...."
4,10202,3304,San Antonio,2792.41,5,None,1,"2 792,41","MULTIPOLYGON (((-84.11975 9.91097, -84.11892 9..."

In [15]:
gdf_densidad = gdf_densidad.drop(columns=[
    "id",
    "value",
    "source",
    "qualitative_value",
    "notes",
    "geometry"
])

In [19]:
print("Head:")
display(gdf_densidad.head())

Head:

  codigo_pcd         nom_es  label_value
0      10101         Carmen      1831.21
1      10102         Merced      7091.74
2      10111  San Sebastián     10702.44
3      10201         Escazú      2870.54
4      10202    San Antonio      2792.41

In [20]:
gdf_densidad.to_csv(
    "densidad_poblacion_distritos.csv",
    index=False,
    encoding="utf-8-sig"
)

In [ ]:
print("\nInfo:")
gdf_densidad.info()
print("\nValores únicos por columna:")
print(gdf_densidad.nunique())


print("codigo_pcd")
print("Mínimo:", gdf_densidad["codigo_pcd"].min())
print("Máximo:", gdf_densidad["codigo_pcd"].max())

print("\nnom_es")
print("Mínimo:", gdf_densidad["nom_es"].min())
print("Máximo:", gdf_densidad["nom_es"].max())

print("\nlabel_value")
print("Mínimo:", gdf_densidad["label_value"].min())
print("Máximo:", gdf_densidad["label_value"].max())

Info:
<class 'pandas.DataFrame'>
RangeIndex: 491 entries, 0 to 490
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   codigo_pcd   491 non-null    str
 1   nom_es       491 non-null    str
 2   label_value  491 non-null    float64
dtypes: float64(1), str(2)
memory usage: 18.5 KB
codigo_pcd
Mínimo: 10101
Máximo: 70605

nom_es
Mínimo: Acapulco
Máximo: Ángeles

label_value
Mínimo: 7.63
Máximo: 29359.8